# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charbattler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='char1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char1', to='charbattler.Character'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='char2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char2', to='charbattler.Character'),
        ),
    ]
