# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charbattler', '0002_auto_20170706_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='losses',
            new_name='total_losses',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='wins',
            new_name='total_wins',
        ),
    ]
